/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.ripper.todoapp.entities;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
