/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.ripper.todoapp.dao;

import net.ripper.todoapp.entities.Todo;
import net.ripper.todoapp.entities.User;
import org.springframework.data.repository.CrudRepository;

public interface TodoRepository extends CrudRepository<Todo, Integer> {
    Iterable<Todo> findAllByOwnerUser(User user);
}
